title: Jordan Pitman
description: Long Form Jekyll theme built with SASS

url: https://jordan-pitman.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact
    - title: Publications
      url: /publications

social:
    github: jordan-pitman
    twitter: #brianmaierjr
    facebook: #brianmaierjr
    email: jordangpitman@gmail.com
    linkedin: linkedin.com/in/jordan-pitman
    youtube: #RickAstleyYT
    tumblr: #i-am-a-fish

google_analytics: #"UA-58263416-1"

disqus:
    shortname: jordan-pitman
